"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { Check, Circle, PackageCheck, Search, Truck, XCircle } from "lucide-react";
import { useLanguage } from "@/context/LanguageContext";
import { formatPrice } from "@/lib/i18n";

const STEPS = ["under_review", "confirmed", "preparing", "out_for_delivery", "delivered"];
const LABELS:any = { nl:{under_review:"Onder beoordeling",confirmed:"Bevestigd",preparing:"Wordt voorbereid",out_for_delivery:"Onderweg",delivered:"Bezorgd",cancelled:"Geannuleerd",title:"Volg je bestelling",subtitle:"Vul je orderreferentie en telefoonnummer in.",reference:"Orderreferentie",phone:"Telefoonnummer",track:"Bestelling volgen",notFound:"Bestelling niet gevonden. Controleer je gegevens.",order:"Bestelling",total:"Totaal",items:"Producten"}, en:{under_review:"Under review",confirmed:"Confirmed",preparing:"Preparing",out_for_delivery:"Out for delivery",delivered:"Delivered",cancelled:"Cancelled",title:"Track your order",subtitle:"Enter your order reference and phone number.",reference:"Order reference",phone:"Phone number",track:"Track order",notFound:"Order not found. Check your details.",order:"Order",total:"Total",items:"Items"} };

export default function TrackOrderPage(){
 const {lang}=useLanguage(); const t=LABELS[lang];
 const [reference,setReference]=useState(""); const [phone,setPhone]=useState(""); const [order,setOrder]=useState<any>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");setLoading(true);setOrder(null);try{const r=await fetch("/api/orders/track",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber:reference,phone})});const d=await r.json();if(!r.ok)throw new Error(d.error);setOrder(d)}catch(e:any){setError(e.message||t.notFound)}finally{setLoading(false)}};
 const current=order?.status; const cancelled=current==="cancelled";
 return <main className="min-h-[75vh] bg-[#faf8f2]"><div className="container-page py-14 sm:py-20 max-w-5xl">
  <div className="max-w-2xl"><p className="text-xs uppercase tracking-[.2em] font-bold text-emerald-800">WIN & WIN FRESH</p><h1 className="mt-3 text-4xl sm:text-5xl font-black tracking-tight">{t.title}</h1><p className="mt-3 text-stone-500">{t.subtitle}</p></div>
  <form onSubmit={submit} className="mt-8 bg-white border border-stone-200 rounded-2xl p-5 sm:p-6 grid md:grid-cols-[1fr_1fr_auto] gap-4 items-end shadow-sm"><label><span className="text-xs font-bold text-stone-600">{t.reference}</span><input value={reference} onChange={e=>setReference(e.target.value.toUpperCase())} placeholder="WWF-2026-..." required className="mt-1.5 w-full h-12 rounded-xl border border-stone-200 px-4 font-semibold outline-none focus:border-emerald-700"/></label><label><span className="text-xs font-bold text-stone-600">{t.phone}</span><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+31 ..." required className="mt-1.5 w-full h-12 rounded-xl border border-stone-200 px-4 outline-none focus:border-emerald-700"/></label><button disabled={loading} className="h-12 px-6 rounded-xl bg-emerald-900 text-white font-bold flex items-center justify-center gap-2 disabled:opacity-60"><Search className="w-4"/>{loading?"...":t.track}</button></form>
  {error&&<div className="mt-4 rounded-xl border border-red-100 bg-red-50 text-red-800 p-4 text-sm">{error}</div>}
  {order&&<section className="mt-8 bg-white border border-stone-200 rounded-3xl p-6 sm:p-8">
   <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs text-stone-500">{t.order}</p><h2 className="text-2xl font-black text-emerald-950">{order.orderNumber}</h2></div><div className={`px-3 py-2 rounded-full text-xs font-bold ${cancelled?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-800"}`}>{t[current]||current}</div></div>
   {cancelled?<div className="mt-8 flex gap-4 p-5 rounded-2xl bg-red-50 text-red-800"><XCircle className="w-6"/><div><p className="font-bold">{t.cancelled}</p></div></div>:<div className="mt-10 grid md:grid-cols-5 gap-3">{STEPS.map((step,i)=>{const reached=STEPS.indexOf(current)>=i;const active=current===step;return <div key={step} className="relative"><div className={`flex md:flex-col items-center md:items-start gap-3 ${reached?"text-emerald-900":"text-stone-300"}`}><div className={`w-9 h-9 rounded-full grid place-items-center border-2 ${reached?"border-emerald-700 bg-emerald-700 text-white":"border-stone-200 bg-white"}`}>{reached?<Check className="w-4"/>:<Circle className="w-3"/>}</div><div><p className={`text-xs font-bold ${active?"text-emerald-900":""}`}>{t[step]}</p><p className="text-[10px] text-stone-400 mt-1">{order.statusHistory?.find((h:any)=>h.status===step)?new Date(order.statusHistory.find((h:any)=>h.status===step).createdAt).toLocaleDateString(lang==="nl"?"nl-NL":"en-GB"):""}</p></div></div></div>})}</div>}
   <div className="mt-10 border-t border-stone-100 pt-6"><h3 className="font-bold">{t.items}</h3><div className="mt-4 space-y-3">{order.items.map((i:any)=><div key={i.productName} className="flex gap-3 items-center"><img src={i.productImage} className="w-12 h-12 rounded-xl object-cover bg-stone-50"/><div className="flex-1"><p className="text-sm font-semibold">{i.productName}</p><p className="text-xs text-stone-500">{i.quantity} {i.unit}</p></div><strong>{formatPrice(i.totalPrice,lang)}</strong></div>)}</div><div className="mt-5 flex justify-end text-lg font-black">{t.total}: <span className="ml-2 text-emerald-900">{formatPrice(order.total,lang)}</span></div></div>
  </section>}
  <div className="mt-6 text-center"><Link href="/shop" className="text-sm font-bold text-emerald-900">← {lang==="nl"?"Verder winkelen":"Continue shopping"}</Link></div>
 </div></main>
}
