import { pgTable, serial, text, numeric, integer, boolean, timestamp, jsonb } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

export const admins = pgTable("admins", {
  id: serial("id").primaryKey(), email: text("email").notNull().unique(), name: text("name").notNull(), passwordHash: text("password_hash").notNull(), role: text("role").notNull().default("manager"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
export const categories = pgTable("categories", {
  id: serial("id").primaryKey(), slug: text("slug").notNull().unique(), nameNl: text("name_nl").notNull(), nameEn: text("name_en").notNull(), descriptionNl: text("description_nl").default(""), descriptionEn: text("description_en").default(""), image: text("image").notNull(), isActive: boolean("is_active").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
export const products = pgTable("products", {
  id: serial("id").primaryKey(), slug: text("slug").notNull().unique(), nameNl: text("name_nl").notNull(), nameEn: text("name_en").notNull(), descriptionNl: text("description_nl").default(""), descriptionEn: text("description_en").default(""), categoryId: integer("category_id").references(() => categories.id, { onDelete: "set null" }), pricePerKg: numeric("price_per_kg", { precision: 10, scale: 2 }).notNull(), salePricePerKg: numeric("sale_price_per_kg", { precision: 10, scale: 2 }), unit: text("unit").default("piece").notNull(), mainImage: text("main_image").notNull(), additionalImages: jsonb("additional_images").$type<string[]>().default([]), stockQuantity: numeric("stock_quantity", { precision: 10, scale: 2 }).default("150.00").notNull(), stockStatus: text("stock_status").default("in_stock").notNull(), origin: text("origin").default("Nederland").notNull(), isFeatured: boolean("is_featured").default(false).notNull(), isSeasonal: boolean("is_seasonal").default(false).notNull(), isOrganic: boolean("is_organic").default(false).notNull(), isNew: boolean("is_new").default(false).notNull(), badges: jsonb("badges").$type<string[]>().default([]), isPublished: boolean("is_published").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull(), nutrition: jsonb("nutrition").$type<Record<string, string>>(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull(),
});
export const productVariants = pgTable("product_variants", { id: serial("id").primaryKey(), productId: integer("product_id").references(() => products.id, { onDelete: "cascade" }).notNull(), titleNl: text("title_nl").notNull(), titleEn: text("title_en").notNull(), weightKg: numeric("weight_kg", { precision: 10, scale: 2 }).notNull(), price: numeric("price", { precision: 10, scale: 2 }).notNull(), stock: integer("stock").default(50).notNull(), isActive: boolean("is_active").default(true).notNull() });
export const orders = pgTable("orders", { id: serial("id").primaryKey(), orderNumber: text("order_number").notNull().unique(), confirmationToken: text("confirmation_token").notNull().unique().default(sql`gen_random_uuid()::text`), customerName: text("customer_name").notNull(), customerEmail: text("customer_email").notNull(), customerPhone: text("customer_phone").notNull(), street: text("street").notNull(), houseNumber: text("house_number").notNull(), postalCode: text("postal_code").notNull(), city: text("city").notNull(), country: text("country").default("Nederland").notNull(), addressExtra: text("address_extra").default(""), orderNotes: text("order_notes").default(""), status: text("status").default("under_review").notNull(), subtotal: numeric("subtotal", { precision: 10, scale: 2 }).notNull(), deliveryFee: numeric("delivery_fee", { precision: 10, scale: 2 }).notNull(), discountAmount: numeric("discount_amount", { precision: 10, scale: 2 }).default("0.00").notNull(), couponCode: text("coupon_code"), total: numeric("total", { precision: 10, scale: 2 }).notNull(), paymentStatus: text("payment_status").default("pending_on_delivery").notNull(), paymentMethod: text("payment_method").default("on_delivery").notNull(), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const orderStatusHistory = pgTable("order_status_history", { id: serial("id").primaryKey(), orderId: integer("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), status: text("status").notNull(), note: text("note").default(""), createdAt: timestamp("created_at").defaultNow().notNull() });
export const orderItems = pgTable("order_items", { id: serial("id").primaryKey(), orderId: integer("order_id").references(() => orders.id, { onDelete: "cascade" }).notNull(), productId: integer("product_id").references(() => products.id, { onDelete: "set null" }), productName: text("product_name").notNull(), pricePerUnit: numeric("price_per_unit", { precision: 10, scale: 2 }).notNull(), quantity: numeric("quantity", { precision: 10, scale: 2 }).notNull(), unit: text("unit").default("piece").notNull(), totalPrice: numeric("total_price", { precision: 10, scale: 2 }).notNull(), productImage: text("product_image").default("") });
export const customers = pgTable("customers", { id: serial("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), phone: text("phone").notNull(), totalOrders: integer("total_orders").default(1).notNull(), totalSpent: numeric("total_spent", { precision: 10, scale: 2 }).default("0.00").notNull(), lastOrderDate: timestamp("last_order_date").defaultNow().notNull(), notes: text("notes").default(""), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const homepageSections = pgTable("homepage_sections", { id: serial("id").primaryKey(), sectionType: text("section_type").notNull(), titleNl: text("title_nl").notNull(), titleEn: text("title_en").notNull(), subtitleNl: text("subtitle_nl").default(""), subtitleEn: text("subtitle_en").default(""), contentNl: text("content_nl").default(""), contentEn: text("content_en").default(""), imageUrl: text("image_url").default(""), buttonTextNl: text("button_text_nl").default(""), buttonTextEn: text("button_text_en").default(""), buttonLink: text("button_link").default(""), isActive: boolean("is_active").default(true).notNull(), sortOrder: integer("sort_order").default(0).notNull(), config: jsonb("config").$type<Record<string, any>>().default({}), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const media = pgTable("media", { id: serial("id").primaryKey(), name: text("name").notNull(), url: text("url").notNull(), folder: text("folder").default("products").notNull(), size: integer("size").default(0), mimeType: text("mime_type").default("image/jpeg"), altNl: text("alt_nl").default(""), altEn: text("alt_en").default(""), createdAt: timestamp("created_at").defaultNow().notNull() });
export const promotions = pgTable("promotions", { id: serial("id").primaryKey(), titleNl: text("title_nl").notNull(), titleEn: text("title_en").notNull(), descriptionNl: text("description_nl").default(""), descriptionEn: text("description_en").default(""), promoBadge: text("promo_badge").default("ACTIE"), bannerImage: text("banner_image").default(""), discountPercentage: numeric("discount_percentage", { precision: 5, scale: 2 }), startDate: timestamp("start_date"), endDate: timestamp("end_date"), isActive: boolean("is_active").default(true).notNull(), linkUrl: text("link_url").default("/shop"), createdAt: timestamp("created_at").defaultNow().notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const coupons = pgTable("coupons", { id: serial("id").primaryKey(), code: text("code").notNull().unique(), discountType: text("discount_type").notNull().default("percentage"), discountValue: numeric("discount_value", { precision: 10, scale: 2 }).notNull(), minOrderAmount: numeric("min_order_amount", { precision: 10, scale: 2 }).default("0.00").notNull(), maxUses: integer("max_uses"), usedCount: integer("used_count").default(0).notNull(), expiresAt: timestamp("expires_at"), isActive: boolean("is_active").default(true).notNull(), createdAt: timestamp("created_at").defaultNow().notNull() });
export const deliverySettings = pgTable("delivery_settings", { id: serial("id").primaryKey(), deliveryFee: numeric("delivery_fee", { precision: 10, scale: 2 }).default("4.95").notNull(), freeDeliveryThreshold: numeric("free_delivery_threshold", { precision: 10, scale: 2 }).default("35.00").notNull(), minOrderValue: numeric("min_order_value", { precision: 10, scale: 2 }).default("15.00").notNull(), deliveryZones: jsonb("delivery_zones").$type<string[]>().default(["Amsterdam", "Rotterdam", "Den Haag", "Utrecht", "Haarlem", "Almere", "Amstelveen", "Zaandam"]).notNull(), deliveryTimeWindow: text("delivery_time_window").default("Binnen 24-48 uur gekoeld bezorgd").notNull(), deliveryNotesNl: text("delivery_notes_nl").default("Gekoelde verslevering rechtstreeks aan uw deur. Maandag t/m zaterdag bezorgd.").notNull(), deliveryNotesEn: text("delivery_notes_en").default("Refrigerated fresh delivery straight to your door. Delivered Monday to Saturday.").notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });
export const storeSettings = pgTable("store_settings", { id: serial("id").primaryKey(), storeName: text("store_name").default("WIN & WIN FRESH BV").notNull(), logoUrl: text("logo_url").default("/images/logo.svg").notNull(), phone: text("phone").default("+31 20 894 3320").notNull(), email: text("email").default("info@winandwinfresh.nl").notNull(), address: text("address").default("Koopliedenweg 14, 1013 AB Amsterdam, Nederland").notNull(), kvkNumber: text("kvk_number").default("87492011").notNull(), vatNumber: text("vat_number").default("NL864321908B01").notNull(), openingHoursNl: text("opening_hours_nl").default("Maandag - Zaterdag: 07:00 - 18:00").notNull(), openingHoursEn: text("opening_hours_en").default("Monday - Saturday: 07:00 - 18:00").notNull(), currency: text("currency").default("EUR").notNull(), defaultLanguage: text("default_language").default("nl").notNull(), whatsappNumber: text("whatsapp_number").default("+31612345678").notNull(), instagramUrl: text("instagram_url").default("https://instagram.com/winandwinfresh").notNull(), facebookUrl: text("facebook_url").default("https://facebook.com/winandwinfresh").notNull(), updatedAt: timestamp("updated_at").defaultNow().notNull() });