"use client";

import Link from "next/link";
import { ArrowRight, Minus, Plus, ShoppingBag, Trash2, Truck } from "lucide-react";
import { useCart } from "@/context/CartContext";
import { useLanguage } from "@/context/LanguageContext";
import { formatPrice } from "@/lib/i18n";

export default function CartPage(){
  const {lang,t}=useLanguage(); const cart=useCart();
  return <div className="min-h-[70vh] bg-[#faf8f2]"><div className="container-page py-10 sm:py-14"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-800">{t.nav.cart}</p><h1 className="mt-2 text-4xl font-black tracking-tight">{t.cart.title}</h1></div>
    {cart.items.length===0?<div className="surface mt-8 p-12 text-center bg-white"><div className="mx-auto w-16 h-16 rounded-full bg-emerald-50 grid place-items-center text-emerald-800"><ShoppingBag/></div><h2 className="mt-5 text-xl font-bold">{t.cart.emptyTitle}</h2><p className="mt-2 text-stone-500">{t.cart.emptyDesc}</p><Link href="/shop" className="inline-flex mt-6 h-11 px-6 rounded-xl bg-emerald-900 text-white items-center gap-2 font-semibold">{t.cart.startShopping}<ArrowRight className="w-4"/></Link></div>:
    <div className="grid lg:grid-cols-[1fr_380px] gap-7 mt-8 items-start"><div className="space-y-3">{cart.items.map(item=>{const unitLabel=item.pricingType==="kg"?"kg":item.pricingType==="pack"?(lang==="nl"?`pack van ${item.packQuantity} stuks`:`pack of ${item.packQuantity} pieces`):(lang==="nl"?"stuk":"piece");return <div key={item.id} className="surface bg-white p-4 sm:p-5 flex gap-4"><Link href={`/product/${item.slug}`} className="w-24 h-24 sm:w-28 sm:h-28 rounded-xl bg-stone-50 overflow-hidden shrink-0"><img src={item.image} alt="" className="w-full h-full object-cover"/></Link><div className="min-w-0 flex-1"><Link href={`/product/${item.slug}`} className="font-bold text-stone-900 hover:text-emerald-800">{lang==="nl"?item.nameNl:item.nameEn}</Link><p className="mt-1 text-sm text-stone-500">{formatPrice(item.pricePerKg,lang)} / {unitLabel}</p><div className="mt-4 flex items-center justify-between gap-3"><div className="inline-flex items-center rounded-lg border border-stone-200 p-1"><button onClick={()=>cart.updateQuantity(item.id,item.quantity-1)} className="w-8 h-8 grid place-items-center"><Minus className="w-3.5"/></button><span className="w-16 text-center text-sm font-bold">{item.quantity} {unitLabel}</span><button onClick={()=>cart.updateQuantity(item.id,item.quantity+1)} className="w-8 h-8 grid place-items-center"><Plus className="w-3.5"/></button></div><div className="text-right"><p className="font-black text-emerald-900">{formatPrice(item.pricePerKg*item.quantity,lang)}</p><button onClick={()=>cart.removeItem(item.id)} className="mt-1 text-xs text-stone-400 hover:text-red-600 inline-flex items-center gap-1"><Trash2 className="w-3.5"/>Remove</button></div></div></div></div>})}<button onClick={cart.clearCart} className="text-xs text-stone-500 hover:text-red-600">{t.cart.clearCart}</button></div>
    <aside className="surface bg-white p-6 sticky top-28">{!cart.isFreeDelivery&&cart.amountNeededForFreeDelivery>0&&<div className="rounded-xl bg-emerald-50 border border-emerald-100 p-4 mb-5"><div className="flex gap-2"><Truck className="w-4 h-4 text-emerald-800 mt-0.5"/><p className="text-xs leading-5 text-emerald-950">{t.cart.freeDeliveryNotice} <strong>{formatPrice(cart.freeDeliveryThreshold,lang)}</strong>. {t.cart.freeDeliveryRemaining} <strong>{formatPrice(cart.amountNeededForFreeDelivery,lang)}</strong>.</p></div></div>}<h2 className="font-bold text-lg">{lang==="nl"?"Overzicht bestelling":"Order summary"}</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-stone-500">{t.cart.subtotal}</span><strong>{formatPrice(cart.subtotal,lang)}</strong></div><div className="flex justify-between"><span className="text-stone-500">{t.cart.deliveryFee}</span><strong>{cart.deliveryFee===0?t.cart.freeDelivery:formatPrice(cart.deliveryFee,lang)}</strong></div>{cart.discountAmount>0&&<div className="flex justify-between text-red-700"><span>{t.cart.discount}</span><strong>-{formatPrice(cart.discountAmount,lang)}</strong></div>}<div className="border-t border-stone-100 pt-4 flex justify-between text-lg"><span className="font-bold">{t.cart.total}</span><strong className="text-emerald-900">{formatPrice(cart.total,lang)}</strong></div></div><Link href="/checkout" className="mt-6 w-full h-12 rounded-xl bg-emerald-900 hover:bg-emerald-950 text-white font-bold flex items-center justify-center gap-2">{t.cart.checkoutButton}<ArrowRight className="w-4"/></Link><p className="mt-4 text-center text-[11px] text-stone-500">{t.cart.note}</p></aside></div>}
  </div></div>
}
